### ISSUE TITLE
[BUG]App UI stretches beyond viewport when user is on mobile device - laredotornado

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#110]
Steps to reproduce

1. Enter the Heroku app on mobile
2. Observe any page in the app

Expected result: App can fit the screen size of the mobile device and the user can see the entire UI.

Actual result:  the UI stretches beyond the current viewport of the mobile device.

**Comment by mat10tng** [comment]
This is fixed! Can you QA again ?

**Comment by CSumm** [comment]
It still occurs on the heroku staging build on my mobile browser

**Comment by azmainamin** [comment]
Can we get an additional QA on this? @mat10tng @CSumm

**Comment by mat10tng** [comment]
yeah, so there is no problem on my mobile, but I am guessing that is not true

**Comment by DalerLeo** [comment]
can go for it?

**Comment by CSumm** [comment]
@azmainamin I checked both on Chrome for mobile and on built in phone browser, and both have issue of page stretching. It seems that the page stretches until you resize it manually after page load

**Comment by azmainamin** [comment]
@CSumm you are correct. There is a PR up for the fix I believe.

**Comment by CSumm** [comment]
This appears to be fixed on mobile. Closing issue
